site_name: TinyGo LilyGo Drivers
site_url: https://dimajolkin.github.io/tinygo-lilygo-drivers/

repo_name: dimajolkin/tinygo-lilygo-drivers
repo_url: https://github.com/dimajolkin/tinygo-lilygo-drivers

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Home: index.md
